name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 3:21
    - cron: '21 3 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Install asv
      run: |
       python -m pip install asv
       python -m pip install pipx
       python -m pipx install virtualenv
    - name: Install jsonschema
      run: python -m pip install jsonschema
    - name: Run benchmark
      run: |
        pwd 
        asv machine --yes 
        python --version
        which python
        asv run ALL
