name: CI

on:
  push:
    branches: 
      - benchmark_asv
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 3:21
    - cron: '21 3 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version:
          - name: pypy2
            toxenv: pypy2-build
          - name: pypy2
            toxenv: pypy2-tests
          - name: pypy2
            toxenv: pypy2-tests_nongpl
          - name: pypy2
            toxenv: safety
              
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version.name }}
    - name: Ensure we have new enough versions to respect python_version
      run: python -m pip install -U pip setuptools
    - name: Install dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install -y libenchant-dev libxml2-dev libxslt-dev
      if: runner.os == 'Linux' && startsWith(matrix.python-version.toxenv, 'docs-')
    - name: Install dependencies
      run: brew install enchant
      if: runner.os == 'macOS' && startsWith(matrix.python-version.toxenv, 'docs-')
    - name: Install tox
      run: python -m pip install tox
    - name: Use venv on Windows
      run: python -m pip install tox-venv
      if: runner.os == 'Windows'
    - name: Run tox
      run: python -m tox -e "${{ matrix.python-version.toxenv }}"
    - name: Install asv
      run: python -m pip install asv
    - name: Run benchmark
      run: |
        pwd 
        asv machine --yes 
        asv check
